routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Main 
Route::get('/', 'HomeController@index')->name('index');


Route::get('/home', function () {
    return redirect()->route('admin.index');
});

// Defaul User Management
Route::get('/admin/dashboard', function () {
    // return view('layouts.admin.master');    
});

Auth::routes(['verify' => true]);

Route::patch('user/password/update', 'UserController@passwordUpdate')->name('user.password.update');
Route::get('user/password/change', 'UserController@changePassword')->name('user.password.change');

// Admin Dashboard 
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['verified']], function(){

    // Admin Dashboard
    Route::get('/dashboard', 'Admin\AdminController@index')->name('index');

    // DataTables
    Route::get('/dashboard/datatables/user', 'DatatablesController@userData')->name('datatables.user');

    // Individual Profile 
    Route::patch('/dashboard/profile/update/{user}', 'ProfileController@update')->name('profile.update');
    Route::get('/dashboard/profile/{user}/edit', 'ProfileController@edit')->name('profile.edit');

    // Users
    Route::resource('/dashboard/users', 'UserController');

});

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use App\Notifications\ResetPasswordEmailNotification;
use App\Notifications\VerifyEmailNotification;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname','middlename', 'lastname', 'is_active','email_verified_at','password_change_at', 'email', 'password','provider', 'provider_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // Customize Send Reset Password Email
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordEmailNotification($token));
    }

    // Customize Send Verification Email
    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmailNotification);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User as Model;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;

use Illuminate\Support\Str;

use Illuminate\Support\Facades\Mail;
use App\Mail\RegisterUser;
use Hash;

use App\Http\Requests\UserStoreRequest;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        
        $this->middleware('role:super admin|branch admin', ['only' => ['index','create']]);

        $this->middleware('check.under.branches');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('user.index');
    }

    public function create()
    {
        $roles = Role::all();
        $userRole = auth()->user()->getRoleNames()->first();
        return view('user.create', compact('branches','roles','userRole'));
    }
    
    public function edit(Model $user)
    {
        $roles = Role::all();
        $userRole = auth()->user()->getRoleNames()->first();
        return view('user.edit', compact('user','branches','roles', 'userRole'));
    }

    public function update($id)
    {
        request()->validate([
            'firstname' => ['required', 'string', 'max:255'],
            'lastname' => ['required', 'string', 'max:255'],
        ]);

        $user = Model::find($id);
        $user->firstname     = request()->firstname;
        $user->middlename    = request()->middlename;
        $user->lastname      = request()->lastname;
        $user->is_active     = request()->status;
        // $user->password      = bcrypt(request()->password);
        $user->save();
        
        // Remove Role From User
        $user->removeRole($user->getRoleNames()->first());

        // Assign Role To User
        $this->assignUserRole($user, request()->role);

        return redirect()->route('admin.users.index')->with('success', 'User is successfully updated.');

    }

    public function store(UserStoreRequest $request)
    {
        $randomPass = Str::random();
        $user = Model::create([
            'firstname'     => $request->firstname,
            'middlename'    => $request->middlename,
            'lastname'      => $request->lastname,
            'email'         => $request->email,
            'is_active'     => '1',
            'password'      => bcrypt($randomPass),
        ]);

        // Send Mail for new registered user
        Mail::to($user->email)->send(new RegisterUser($user, $randomPass));

        // Assign Role
        $this->assignUserRole($user, $request->role);

        return redirect()->route('admin.users.index')->with('success', 'User is successfully created.');
    }

    public function destroy($status)
    {
        $user = Model::find(request()->user_id)->delete();

        return redirect()->route('admin.users.index')->with('success', 'User is successfully deleted.');
    }

    public function assignUserRole($user, $role)
    {
        $user->assignRole($role);
    }

    public function changePassword()
    {
        return view('auth.passwords.change-password');
    }

    public function passwordUpdate()
    {
        if (!Hash::check(request()->current_password, auth()->user()->password)) {
            return back()->with('invalid_current_pass', 'Current password is not existing.');
        }

        request()->validate([
            'password' => ['required', 'string', 'min:6', 'confirmed'],
            'current_password' => ['required'],
        ]);

        $user = Model::find(auth()->user()->id);
        $user->password = bcrypt(request()->password);
        $user->password_change_at = \Carbon\Carbon::now();
        $user->email_verified_at = \Carbon\Carbon::now();
        $user->save();

        return redirect()->route('admin.index')->with('success', 'Password is successfully updated.');
        
    }

}

resources/views/user/create.blade.php
@extends('layouts.dashboard.master')

@section('content')
<div class="custom-container">
    <div class="row">
        <div class="col-md-12">
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>
                        User Management 
                    </h1>
                    <p></p>
                    {{-- <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol> --}}
                </section>
                <div class="col-md-6">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Add User</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form action="{{ route('admin.users.store') }}" method="POST">
                            @csrf
                            <div class="box-body">
                                <div class="form-group {{ $errors->has('firsname') ? 'has-error' : '' }}">
                                    <label for="firstname">First name*</label>
                                    <input type="text" class="form-control" id="firstname" name="firstname" value="{{ old('firstname') }}" required>
                                    @if ($errors->has('firstname'))
                                        <span class="help-block">{{ $errors->first('firstname') }}</span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="middlename">Middle name</label>
                                    <input type="text" class="form-control" id="middlename" name="middlename" value="{{ old('middlename') }}" >
                                </div>
                                <div class="form-group {{ $errors->has('lastname') ? 'has-error' : '' }}">
                                    <label for="lastname">Last name*</label>
                                    <input type="text" class="form-control" id="lastname" name="lastname" value="{{ old('lastname') }}"  required>
                                    @if ($errors->has('lastname'))
                                        <span class="help-block">{{ $errors->first('lastname') }}</span>
                                    @endif
                                </div>
                                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                    <label for="email">Email*</label>
                                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
                                    @if ($errors->has('email'))
                                        <span class="help-block">{{ $errors->first('email') }}</span>
                                    @endif
                                </div>
                                {{-- <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                                    <label for="password">Password*</label>
                                    <input type="password" class="form-control" id="password" name="password" required>
                                    @if ($errors->has('password'))
                                        <span class="help-block">{{ $errors->first('password') }}</span>
                                    @endif
                                </div>
                                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                                    <label for="password_confirmation">Confirm Password*</label>
                                    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" required>
                                </div> --}}
                                <div class="form-group">
                                    <label for="role">Role*</label>
                                    <select class="form-control" id="role" name="role" required>
                                        <option style="display:none;">Select Role</option>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->name }}" 
                                                {{ old('role') == $role->name ? 'selected' : '' }}
                                                {{ $userRole == 'branch admin' ? ($role->name == 'agent' ? 'selected' : '') : '' }}
                                                >{{ ucwords($role->name) }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                    
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('after-scripts')
<script>
</script>
@endpush

<style>
.custom-container{
    background: #ecf0f5;
}
</style>
      
      

resources/views/user/edit.blade.php
@extends('layouts.dashboard.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>
                        User Management
                    </h1>
                    <p></p>
                    {{-- <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol> --}}
                </section>
                <div class="col-md-6">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit User</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form action="{{ route('admin.users.update', $user->id) }}" method="POST">
                            @csrf
                            @method('patch')
                            <div class="box-body">
                                <div class="form-group {{ $errors->has('firsname') ? 'has-error' : '' }}">
                                    <label for="firstname">First name*</label>
                                    <input type="text" class="form-control" id="firstname" name="firstname" value="{{ $user->firstname }}" required>
                                    @if ($errors->has('firstname'))
                                        <span class="help-block">{{ $errors->first('firstname') }}</span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="middlename">Middle name</label>
                                    <input type="text" class="form-control" id="middlename" name="middlename" value="{{ $user->middlename  }}">
                                </div>
                                <div class="form-group {{ $errors->has('lastname') ? 'has-error' : '' }}">
                                    <label for="lastname">Last name*</label>
                                    <input type="text" class="form-control" id="lastname" name="lastname" value="{{ $user->lastname  }}" required>
                                    @if ($errors->has('lastname'))
                                        <span class="help-block">{{ $errors->first('lastname') }}</span>
                                    @endif
                                </div>
                                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                    <label for="email">Email*</label>
                                    <input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}" disabled>
                                    @if ($errors->has('email'))
                                        <span class="help-block">{{ $errors->first('email') }}</span>
                                    @endif
                                </div>
                                {{-- <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                                    <label for="password">Password*</label>
                                    <input type="password" class="form-control" id="password" name="password" >
                                    @if ($errors->has('password'))
                                        <span class="help-block">{{ $errors->first('password') }}</span>
                                    @endif
                                </div>
                                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                                    <label for="password_confirmation">Confirm Password*</label>
                                    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" >
                                </div> --}}
                                <div class="form-group {{ $errors->has('status') ? 'has-error' : '' }}">
                                    <label for="role">Status*</label>
                                    <select class="form-control" id="role" name="status" >
                                        <option style="display:none;">Select status</option>
                                        <option value="1" {{ (int)$user->is_active == 1 ? 'selected' : ''}}>Active</option>
                                        <option value="0" {{ (int)$user->is_active == 0 ? 'selected' : ''}}>Inactive</option>
                                    </select>
                                    @if ($errors->has('status'))
                                        <span class="help-block">{{ $errors->first('status') }}</span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="role">Role*</label>
                                    <select class="form-control" id="role" name="role" required>
                                        <option style="display:none;">Select Role</option>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->name }}" {{ $user->getRoleNames()->first() == $role->name ? 'selected' : '' }}>{{ ucwords($role->name) }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <!-- /.box-body -->
                    
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('after-scripts')
<script>
</script>
@endpush
      
      
      

resources/views/user/index.blade.php
@extends('layouts.dashboard.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>
                        User Management 
                        <small>Active Users</small>
                    </h1>
                    <p></p>
                    @if(session('success'))
                        <div class="callout callout-success">
                        <h4>{{ session('success')}}</h4>
                    @endif
                    {{-- <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol> --}}
                </section>
                <div class="col-md-12">
                    <div class="box box-primary" style="padding: 20px;">
                        <div class="box-header with-border">
                            <h3 class="box-title"></h3>
                            <div class="box-tools pull-right">
                                <a href="{{ route('admin.users.create')}}">
                                    <button type="button" class="btn btn-success btn-xs" ><i class="fa fa-plus"></i> Add User
                                    </button>
                                </a>
                            </div>
                        </div>
                        <table class="table table-bordered" id="users-table">
                            <thead>
                                <tr>
                                    {{-- <th>Id</th> --}}
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <form action="{{ route('admin.users.destroy', 'destroy') }}" method="POST" id="formDelUser">
            @csrf
            @method('delete')
            <input type="hidden" class="user-id" name="user_id" value="">
        </form>
        {{-- <button type="button" class="btn btn-info btn-lg">Open Modal</button> --}}

        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p>Are you sure do you want to delete this user?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-submit-delete">Yes</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
            </div>
            </div>

        </div>
        </div>
    </div>
@endsection
@push('after-scripts')
<script>
    $(document).ready(function(){
        $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('admin.datatables.user') !!}',
            columns: [
                // { data: 'id', name: 'id' },
                { data: 'fullname', name: 'fullname' },
                { data: 'email', name: 'email' },
                { data: 'status', name: 'status', orderable: false, searchable: false },
                { data: 'created_at', name: 'created_at' },
                { data: 'updated_at', name: 'updated_at' },
                { data: 'action', name: 'action', orderable: false, searchable: false },
                // { data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });

    // Delete User
    $(document).on('click', '.btn-delete-user',function(){
        $('.user-id').val($(this).attr('data-id'));
    }); 
    $(document).on('click', '.btn-submit-delete',function(){
        $('#formDelUser').submit();
    }); 

</script>
@endpush